# .github/workflows/ci.yml
name: Ejecutar Tests en Pushes

on:
  push:
    branches:
      - main
      - ENTREGA_2
      - refactor-reservas-notificaciones

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar tests
        run: npm test