# .github/workflows/ci.yml
name: Ejecutar Tests en Pushes

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Instalar dependencias backend
        run: |
          cd backend
          npm ci
        
      - name: Ejecutar tests backend
        run: |
          cd backend
          npm test
